services:
  - type: web
    name: telegram-bot-shop
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPPORT_USERNAME
        sync: false
      - key: SOLANA_ADDRESS
        sync: false
